# K-Fold

In [1]:
# loading library
import os
import numpy as np
import pandas as pd
#For test train split
from sklearn.model_selection import train_test_split
#Loading a confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor

In [2]:
os.chdir(r'C:\Users\Yogesh\Downloads')       #changing the directory
c = pd.read_csv('iris.csv')                  # loading data
c  = c.sample(150)                           #shuffling the data
c

     sepal_length  sepal_width  petal_length  petal_width          species
134           6.1          2.6           5.6          1.4   Iris-virginica
63            6.1          2.9           4.7          1.4  Iris-versicolor
102           7.1          3.0           5.9          2.1   Iris-virginica
122           7.7          2.8           6.7          2.0   Iris-virginica
124           6.7          3.3           5.7          2.1   Iris-virginica
..            ...          ...           ...          ...              ...
147           6.5          3.0           5.2          2.0   Iris-virginica
5             5.4          3.9           1.7          0.4      Iris-setosa
62            6.0          2.2           4.0          1.0  Iris-versicolor
82            5.8          2.7           3.9          1.2  Iris-versicolor
16            5.4          3.9           1.3          0.4      Iris-setosa

[150 rows x 5 columns]

In [3]:
def Kclass(k,n):                                    # function Defnation             
    a = 0                                          # seting zero starting point
    b = int(len(c)/k)                              #converting to int & getiting len fro b 

    for x in range(k):                             #for loop starts
        v = c.iloc[a:b]                            # validation list starts
        v1= v.iloc[:,:4]                           #xTrain / valdidation data
        v2= v.iloc[:,4:5]                          #ytrain / valdidation data prediction
        u = c.iloc[0:a]                            #0 to a train data xtest 
        i = c.iloc[b:len(c)]                       #b to 150 train data xtest        
        a = b                                      #equating a and b for next iteraton
        b = int(b + len(c)/k)                      # find the len of b for last index
        frames = [u, i]                            #combine train data
        r = pd.concat(frames)                      #concate the x train data
        y1 =r.iloc[:,:4]                           #xTrain  
        y2 =r.iloc[:,4:5]                          #ytrain
        y2 = y2.squeeze()                          # to avoid warning
        knn = KNeighborsClassifier(n_neighbors=n)  #Kneighbors selected here
        knn.fit(y1 , y2)                           #fitting the model
        y_pred = knn.predict(v1)                   #getting the predited value
        conf_m= confusion_matrix(v2 , y_pred)      # confusion  matrix  
        print(conf_m)                              # printing confusion matrix 
        t = ((conf_m[0,0]+conf_m[1,1]+conf_m[2,2]) / np.sum(conf_m)) #getting the accuracy
        print(t)                                      # print the accuracy

In [4]:
Kclass(5,5)

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
1.0
[[11  0  0]
 [ 0  9  1]
 [ 0  0  9]]
0.9666666666666667
[[ 8  0  0]
 [ 0  8  0]
 [ 0  2 12]]
0.9333333333333333
[[10  0  0]
 [ 0  9  2]
 [ 0  0  9]]
0.9333333333333333
[[11  0  0]
 [ 0 11  0]
 [ 0  1  7]]
0.9666666666666667

# Regression

In [5]:
os.chdir(r'C:\Users\Yogesh\Downloads')          #changing the directory
p = pd.read_csv('cars.csv')                     # loading the data
p  = p.sample(406)                              #shuffling the data
p

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
162,Ford Maverick,15.0,6,250.0,72,3158,19.5,75,US
12,Ford Torino (sw),0.0,8,351.0,153,4034,11.0,70,US
350,Toyota Starlet,39.1,4,79.0,58,1755,16.9,81,Japan
249,BMW 320i,21.5,4,121.0,110,2600,12.8,77,Europe
348,Chevrolet Citation,23.5,6,173.0,110,2725,12.6,81,US
...,...,...,...,...,...,...,...,...,...
242,Toyota Corolla Liftback,26.0,4,97.0,75,2265,18.2,77,Japan
165,Plymouth Grand Fury,16.0,8,318.0,150,4498,14.5,75,US
343,Ford Mustang Cobra,23.6,4,140.0,0,2905,14.3,80,US
377,Chevrolet Cavalier 2-door,34.0,4,112.0,88,2395,18.0,82,US
139,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US

In [6]:
def Kreg(k,n):
    a = 0                                      # seting a as zero starting point
    b = int(len(p)/k)                          #converting to int & getiting len fro b

    for x in range(k):                         #for loop starts          
        v = p.iloc[a:b]                        # validation list starts
        v1= v.iloc[:,3:7]                      #xTrain / valdidation data
        v2= v.iloc[:,1:2]                      #ytrain / valdidation data prediction
        u = p.iloc[0:a]                        #0 to a train data xtest 
        i = p.iloc[b:len(p)]                   #b to 150 train data xtest
        #i1 = i.iloc[:,4]        
        a = b                                  #equating a and b for next iteraton
        b = int(b + len(p)/k)                  # find the len of b for last index
        frames = [u, i]                        #combine train data
        r = pd.concat(frames)                  #concate the x train data
        y1 =r.iloc[:,3:7]                      #xTrain  
        y2 =r.iloc[:,1:2]                      #ytrain
        knn = KNeighborsRegressor(n_neighbors=n)#Kneighbors selected here 
        knn.fit(y1 , y2)                        #fitting the model
        y_pred = knn.predict(v1)                #getting the predited value
        mean=mean_squared_error(v2,y_pred)      #getting the squared error
        print(mean)                             #mean squared error

In [11]:
Kreg(2,5)

30.450530049261083
24.70456551724138